language: go

go: "1.10"

os:
  - linux

cache:
  directories:
  - ~/util-linux

sudo: required
dist: trusty

env:
  matrix:
    - HYPERKUBE_VERSION=1.11.2
    - HYPERKUBE_VERSION=1.10.7

before_install:
  - sudo apt-get update -qq


install:
  # Override the latest tag by the current branch, in the store.
  # TODO: use the image built by quay for this branch
  - sudo docker build -t quay.io/julienbalestra/kube-csr:master .

  - sudo apt-get install -yq systemd curl autopoint openssl
  - ls -l ~/util-linux/nsenter || bash -xec "mkdir -pv ~/util-linux && curl -Lf https://www.kernel.org/pub/linux/utils/util-linux/v2.24/util-linux-2.24.1.tar.gz | tar -xz --strip-component 1 -C ~/util-linux && ~/util-linux/autogen.sh && pushd ~/util-linux/ && ./configure --without-python --disable-all-programs --enable-nsenter && popd"
  - make -C ~/util-linux -j nsenter
  - sudo cp -v ~/util-linux/nsenter /usr/local/bin

  - sudo curl -Lf https://storage.googleapis.com/kubernetes-release/release/v$HYPERKUBE_VERSION/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
  - sudo chmod +x /usr/local/bin/kubectl
  - sudo curl -Lf https://github.com/DataDog/pupernetes/releases/download/v0.8.0/pupernetes -o /usr/local/bin/pupernetes
  - sudo chmod +x /usr/local/bin/pupernetes

script:
  - make
  - sudo /usr/local/bin/pupernetes daemon run sandbox/ --job-type systemd --hyperkube-version $HYPERKUBE_VERSION --kubeconfig-path $HOME/.kube/config --dns-check
  - make ci-e2e
