version: 2

templates:
  job_template: &job_template
    docker:
      - image: golang:1.10
    working_directory: /go/src/github.com/JulienBalestra/kube-csr

  machine_job_template: &machine_job_template
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/JulienBalestra/kube-csr
    environment:
      DEBIAN_FRONTEND: "noninteractive"
      CFLAGS: ""
      CGO_ENABLED: "1"

jobs:
  make:
    <<: *job_template
    steps:
      - checkout
      - run:
          name: make
          command: make

  tests:
    <<: *job_template
    steps:
      - checkout
      - run:
          name: tests
          command: make check

  gofmt:
    <<: *job_template
    steps:
      - checkout
      - run:
          name: verify-gofmt
          command: make verify-gofmt

  docs:
    <<: *job_template
    steps:
      - checkout
      - run:
          name: verify-docs
          command: make verify-docs

  license:
    <<: *job_template
    steps:
      - checkout
      - run:
          name: verify-license
          command: make verify-license

  misc:
    <<: *job_template
    steps:
      - checkout
      - run:
          name: goget
          command: make goget
      - run:
          name: verify ineffassign golint misspell
          command: make -j verify-misc

  pupernetes:
    <<: *machine_job_template
    steps:
      - checkout
      - run:
          name: docker-image
          # Override the latest tag by the current branch, in the store.
          # TODO: use the image built by quay for this branch
          command: sudo docker build -t quay.io/julienbalestra/kube-csr:latest .
      - run:
          name: kubeconfig
          command: mkdir -pv $HOME/.kube && touch $HOME/.kube/config && sudo ln -sv /home/circleci/.kube /.kube
      - run:
          name: download
          command: sudo curl -Lf https://github.com/DataDog/pupernetes/releases/download/v0.5.0/pupernetes -o /usr/local/bin/pupernetes && sudo chmod +x /usr/local/bin/pupernetes
      - run:
          name: apt
          command: sudo apt-get update -qq && sudo apt-get install -yqq systemd openssl
      - run:
          name: run
          command: sudo /usr/local/bin/pupernetes daemon run sandbox/ --job-type systemd --kubectl-link /usr/local/bin/kubectl
      - run:
          name: make
          command: make
      - run:
          name: cli
          command: ./kube-csr issue e2e --generate --submit --approve --fetch --kubeconfig-path $HOME/.kube/config
      - run:
          name: get-ca
          command: kubectl get secret -o json | jq -re '.items[].data["ca.crt"]' | base64 -d > ca.crt
      - run:
          name: openssl-verify
          command: openssl verify -CAfile ca.crt kube-csr.certificate
      - run:
          name: kubectl
          command: kubectl apply -f examples/etcd.yaml
      - run:
          name: etcd
          command: timeout 600 ./.ci/etcd.sh
      - run:
          name: grace-delete-csr
          command: ./kube-csr garbage-collect --fetched --grace-period=1h --kubeconfig-path $HOME/.kube/config
      - run:
          name: no-delete-csr
          command: ./kube-csr garbage-collect --denied --grace-period=0s --kubeconfig-path $HOME/.kube/config
      - run:
          name: delete-csr
          command: ./kube-csr garbage-collect --fetched --grace-period=0s --kubeconfig-path $HOME/.kube/config

workflows:
  version: 2
  tests:
    jobs:
      - tests

  build:
    jobs:
      - make

  verify:
    jobs:
      - gofmt
      - docs
      - license
      - misc

  e2e:
    jobs:
      - pupernetes